#!/usr/bin/env bash

pgcontents init -l $DATABASE_URL --no-prompt

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user
sudo apt-get update
sudo apt-get install --reinstall build-essential

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port $PORT \
	$JUPYTER_NOTEBOOK_ARGS \
	notebooks
