name: heroku-jupyter
channels:
  - conda-forge
  - defaults
dependencies:
  # Mining the Social Web 3rd Edition Requirements
  - beautifulsoup4
  - blas=1.1=openblas
  - entrypoints
  - fastcache
  - freetype
  - h5py
  - hdf5
  - ipykernel
  - jpype1
  - jsonschema
  - jupyter_client
  - jupyter_core
  - matplotlib
  - networkx
  - numexpr
  - numpy
  - olefile
  - openblas
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pygments
  - pyparsing
  - pyrsistent
  - python-dateutil
  - pytz
  - pyzmq
  - scikit-learn
  - send2trash
  - setuptools
  - sympy
  - terminado
  - testpath
  - toolz
  - traitlets
  - vincent
  - wcwidth
  - webencodings
  - widgetsnbextension
  - xlrd
  - zeromq
  # To be installed via pip
  - pip:
    - asn1crypto==0.24.0
    - async-generator==1.10
    - boilerpipe3==1.1
    - cffi==1.11.5
    - charade==1.0.3
    - cluster==1.4.0
    - envoy==0.0.3
    - facebook-sdk==2.0.0
    - feedparser==5.2.1
    - flask==0.12.3
    - geopy==1.11.0
    - google-api-python-client==1.6.6
    - httplib2==0.12.0
    - itsdangerous==1.1.0
    - jpype1-py3==0.5.5.2
    - mailbox==0.4
    - nltk==3.2.2
    - oauth2client==4.1.3
    - oauthlib==2.1.0
    - pamela==0.3.0
    - prettytable==0.7.2
    - pyasn1==0.4.4
    - pyasn1-modules==0.2.2
    - pycosat==0.6.3
    - pycparser==2.19
    - pycurl==7.43.0.2
    - pygithub==1.35
    - pyjwt==1.7.1
    - pymongo==3.6.1
    - pyopenssl==18.0.0
    - pysocks==1.6.8
    - python-editor==1.0.3
    - python-instagram==1.3.2
    - python-oauth2==1.0.1
    - python3-linkedin==1.0.1
    - requests-oauthlib==1.0.0
    - rsa==4.0
    - ruamel.yaml==0.15.71
    - simplejson==3.16.0
    - simplekml==1.3.0
    - twitter==1.17.1
    - twitter-text==3.0
    - uritemplate==3.0.0
    - urllib3==1.24.1
    - werkzeug==0.14.1
